export const authConstants = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  DELETE_USER: "DELETE_USER",
};

export const userConstants = {
  GET_REALTIME_USERS: "GET_REALTIME_USERS",
  GET_REALTIME_MESSAGES: "GET_REALTIME_MESSAGES",
};
